// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqotmhjzlmtbfrbjvhbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxb3RtaGp6bG10YmZyYmp2aGJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNDgxMzUsImV4cCI6MjA2MzgyNDEzNX0.Y-E9zXsGrzzZxBbDraeHK8FZZgXlhJtLUFh1egZ64Ds";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);